// 単語タップ辞書 — アプリ内に登場する英文の語をカバーする簡易グロッサリー。
// 単語デッキ（app.js の vocabDecks）に載っている語はそちらの ja を使うため、ここには重複して持たない。
// キーは原形。活用形（-s / -ed / -ing など）は app.js の lookupWord() が正規化して引く。

window.WordGlossary = {
  abroad: "海外へ", absorb: "吸収する", academic: "学問の", access: "アクセス・利用",
  accident: "事故", according: "〜によれば", account: "アカウント・口座", action: "行動",
  add: "加える", affordable: "手頃な", afraid: "恐れて・残念ながら", after: "〜の後で",
  afternoon: "午後", again: "もう一度", age: "年齢・長い間", ahead: "前方に・先に",
  air: "空気", airport: "空港", alert: "警報・知らせ", alex: "アレックス（人名）",
  all: "すべて", allow: "許す", almost: "ほとんど", alone: "一人で", already: "すでに",
  also: "また", although: "〜だけれども", amazing: "素晴らしい", an: "一つの",
  anna: "アンナ（人名）", announce: "発表する", annual: "年次の", another: "もう一つの",
  any: "どれか・少しも", anyone: "誰でも", anytime: "いつでも", apartment: "アパート",
  apply: "応募する・適用する", appointment: "予約・約束", appreciate: "感謝する",
  approval: "承認", app: "アプリ", april: "4月", are: "〜である", area: "地域",
  around: "〜のまわり・約", arrive: "到着する", article: "記事", ask: "尋ねる", at: "〜で",
  attend: "出席する", attention: "注意", attractive: "魅力的な", audit: "監査",
  august: "8月", authentication: "認証", author: "著者", automatic: "自動の",
  average: "平均", background: "背景", bag: "かばん", bakery: "パン屋",
  baking: "お菓子作り", balance: "残高・バランス", bar: "バー", barbecue: "バーベキュー",
  battery: "電池", beat: "打ち勝つ・避ける", because: "なぜなら", become: "〜になる",
  been: "（be の過去分詞）", before: "〜の前に", behind: "〜の後ろに・遅れて",
  belief: "信念・通説", best: "最も良い", better: "より良い", between: "〜の間に",
  big: "大きい", bill: "請求書・お会計", bit: "少し", blue: "青", book: "本・予約する",
  borrow: "借りる", boston: "ボストン（地名）", both: "両方", breakfast: "朝食",
  bridge: "橋", briefly: "簡潔に", bring: "持ってくる", brunch: "ブランチ",
  build: "建てる・作る", bus: "バス", business: "仕事・事業", busy: "忙しい",
  but: "しかし", buy: "買う", cafe: "カフェ", calculate: "計算する",
  calendar: "カレンダー", call: "電話（する）・呼ぶ", campaign: "キャンペーン",
  can: "〜できる", "can't": "〜できない", cancel: "中止する", cancellation: "解約",
  careful: "注意深い", carefully: "慎重に", car: "車", case: "場合",
  cast: "投げかける", castle: "城", cause: "原因", cautionary: "戒めの",
  central: "中央の", change: "変える・変更", chapter: "章", chart: "図表",
  chicago: "シカゴ（地名）", chicken: "鶏肉", child: "子ども", choose: "選ぶ",
  churn: "解約率", city: "都市", clarify: "明確にする", class: "授業",
  close: "閉める・近い", clothes: "服", coal: "石炭", coastal: "海岸沿いの",
  coffee: "コーヒー", combine: "組み合わせる", come: "来る", commit: "確約する",
  common: "一般的な", commuting: "通勤", company: "会社", complete: "完了する",
  completely: "完全に", completion: "完了", complex: "複雑な", concede: "認める",
  concern: "懸念", concert: "コンサート", conclusion: "結論", conditioner: "エアコン",
  confuse: "混同する", consideration: "検討", contact: "連絡する", content: "内容",
  contract: "契約", contradict: "反論する", convenient: "便利な",
  conversation: "会話", cooking: "料理", copy: "一冊・複製", core: "中核",
  correlation: "相関", cost: "費用", could: "〜していただけますか",
  country: "国", course: "講座・コース", cover: "補償する・扱う", create: "作る",
  critic: "批判する人", cultural: "文化の", current: "現在の", cut: "削る",
  dallas: "ダラス（地名）", damage: "損なう", dark: "暗い", date: "日付", day: "日",
  dead: "動かない・疲れ切った", dean: "学部長", dear: "拝啓・親愛なる",
  decade: "10年", decide: "決める", deep: "深い", degree: "学位・度", demo: "デモ",
  deserve: "値する", design: "デザイン", desk: "机・受付", develop: "開発する",
  development: "開発", did: "した", different: "異なる", dinner: "夕食",
  directly: "直接", disappear: "消える", discipline: "分野・規律", discount: "割引",
  discuss: "話し合う", discussion: "議論", do: "する", document: "書類",
  "doesn't": "〜しない", dominate: "主流になる", "don't": "〜しない", done: "終わった",
  door: "ドア", doubt: "疑い", downtown: "中心街", drama: "ドラマ",
  draw: "引き出す・描く", dress: "服装", drink: "飲み物", drive: "牽引する・運転する",
  during: "〜の間", each: "それぞれ", early: "早い", economic: "経済の",
  economy: "経済", effect: "効果", effort: "努力", egg: "卵", electric: "電気の",
  elevator: "エレベーター", eleven: "11", email: "メール", employer: "雇用主",
  enable: "有効にする", end: "終わり", energy: "エネルギー", engineering: "工学",
  english: "英語", enjoy: "楽しむ", enrollment: "登録者数", enterprise: "法人・大企業",
  especially: "特に", evening: "夕方", ever: "これまでに", every: "すべての",
  everyone: "みんな", everything: "すべて", exact: "正確な", example: "例",
  excuse: "失礼・許す", exercise: "運動", expect: "予想する", expense: "経費",
  expensive: "高価な", experience: "経験", experiment: "実験", explain: "説明する",
  expression: "表現", extend: "延長する", extra: "追加の", factor: "要因",
  failing: "不合格の", fall: "落ちる・秋", fallen: "落ちた", family: "家族",
  fee: "料金", feel: "感じる", fell: "下がった", festival: "お祭り",
  few: "ほとんどない", field: "分野", fifth: "5番目の", file: "ファイル",
  film: "映画", filter: "フィルター", find: "見つける", finish: "終える",
  first: "最初の", five: "5", fix: "直す", flat: "フラット（コーヒー）・平らな",
  flexibility: "柔軟性", floor: "階", focus: "焦点を当てる", forget: "忘れる",
  forgot: "忘れた", form: "用紙・形", forty: "40", forum: "掲示板", four: "4",
  free: "無料の・空いている", fresh: "新鮮な", friday: "金曜日", friendly: "親切な",
  from: "〜から", front: "前・フロント", frozen: "凍結した", fuel: "燃料",
  full: "いっぱいの・完全な", fun: "楽しみ", future: "未来", gain: "伸び・利益",
  gap: "差", gas: "ガス", gate: "ゲート", gave: "与えた", gentlemen: "紳士（皆様）",
  global: "世界の", glossary: "用語集", go: "行く", goal: "目標",
  gonna: "〜するつもり", got: "得た", government: "政府", graduate: "大学院の・卒業する",
  great: "素晴らしい", grew: "成長した", growth: "成長", guess: "推測する",
  habit: "習慣", had: "持っていた", half: "半分", happy: "嬉しい",
  hard: "難しい・熱心に", has: "持っている", have: "持っている", he: "彼",
  heat: "熱", heater: "ヒーター", heavy: "重い・激しい", hectic: "慌ただしい",
  hello: "こんにちは", help: "助ける", helpful: "役立つ", her: "彼女の",
  here: "ここ", "here's": "ここに〜がある", hey: "やあ", hi: "こんにちは",
  high: "高い", hiking: "ハイキング", hire: "新入社員・雇う", hiring: "採用",
  history: "歴史", home: "家", homesick: "ホームシックの", homework: "宿題",
  honestly: "正直に", hooked: "ハマって", hope: "願う", hot: "暑い",
  hotel: "ホテル", hour: "時間", "how's": "〜はどう？", however: "しかし",
  humanities: "人文科学", i: "私", "i'd": "私は〜したい", "i'll": "私は〜します",
  "i've": "私は〜したことがある", id: "身分証", if: "もし", ignore: "無視する",
  improve: "向上させる", include: "含む", income: "収入", instead: "代わりに",
  interested: "興味がある", interesting: "興味深い", internship: "インターンシップ",
  invitation: "招待", "isn't": "〜ではない", issue: "問題", "it's": "それは〜だ",
  item: "項目", jacket: "ジャケット", january: "1月", jazz: "ジャズ", job: "仕事",
  jogging: "ジョギング", john: "ジョン（人名）", join: "参加する", joint: "共同の",
  june: "6月", just: "ただ・ちょうど", ken: "ケン（人名）", key: "鍵・重要な",
  kitchen: "キッチン", know: "知る", lab: "研究室", lack: "不足",
  ladies: "ご婦人（皆様）", landlord: "大家", language: "言語", last: "最後の・続く",
  later: "後で", launch: "発売・開始", lead: "導く・つながる", leaking: "水漏れしている",
  learning: "学習", least: "最も少ない", leave: "去る・置いていく", lee: "リー（人名）",
  legal: "法務・法律の", leg: "脚", lend: "貸す", let: "〜させる", "let's": "〜しよう",
  library: "図書館", lie: "横たわる・嘘", like: "好き・〜のような", line: "路線・行",
  listen: "聞く", lively: "活気ある", locate: "位置づける", location: "立地",
  long: "長い", longevity: "長寿", lose: "失う", love: "大好き",
  lower: "下げる・より低い", lunch: "昼食", made: "作った", maintain: "主張する・維持する",
  maintenance: "メンテナンス", man: "男性", manager: "管理者", marathon: "マラソン",
  march: "3月", mark: "印をつける", market: "市場", matter: "重要である・問題",
  may: "5月・〜かもしれない", meaning: "意味", medical: "医療の", meet: "会う",
  memory: "記憶", menu: "メニュー", minute: "分", miss: "逃す・恋しく思う",
  mix: "混ぜる", moment: "瞬間", monday: "月曜日", month: "月", more: "もっと",
  morning: "朝", most: "最も", move: "動く・移す", movie: "映画", mr: "〜さん",
  much: "多くの", multitasking: "マルチタスク", museum: "博物館",
  must: "〜しなければならない", my: "私の", name: "名前", near: "近く",
  need: "必要とする", network: "網・ネットワーク", new: "新しい", next: "次の",
  nice: "良い", night: "夜", ninety: "90", noise: "騒音", non: "非〜",
  not: "〜ない", note: "メモ・議事録", now: "今", number: "番号",
  "o'clock": "〜時", october: "10月", off: "離れて・割引で", offer: "提供する",
  offset: "相殺する", often: "よく", oh: "ああ", okinawa: "沖縄", old: "古い",
  once: "一度・かつて", one: "一つ", online: "オンライン", open: "開ける",
  opposite: "反対の", or: "または", original: "元の", our: "私たちの",
  over: "〜を超えて", overrated: "過大評価の", page: "ページ", paper: "紙・論文",
  paragraph: "段落", parking: "駐車場", part: "部分", participation: "参加",
  party: "パーティー", passenger: "乗客", pasta: "パスタ", path: "道",
  pause: "一時停止", pay: "支払う", pencil: "鉛筆", people: "人々", per: "〜につき",
  percent: "パーセント", perfect: "完璧な", person: "人", phase: "段階",
  photo: "写真", physical: "物理的な", picture: "写真", pilot: "試験導入",
  pizza: "ピザ", place: "場所", plan: "計画", please: "どうぞ・お願いします",
  plus: "加えて", policy: "方針・保険", pool: "プール", possible: "可能な",
  post: "投稿する", practical: "実践的な", prefer: "好む", premium: "プレミアムの",
  prepare: "準備する", press: "報道・押す", pressure: "圧力", price: "価格",
  pricey: "高めの", probably: "おそらく", proceed: "進む", productivity: "生産性",
  professor: "教授", program: "プログラム", project: "プロジェクト",
  promotion: "昇進", propose: "提案する", proud: "誇らしい", psa: "お知らせ",
  psychology: "心理学", purchase: "購入", quarter: "四半期", quick: "素早い",
  quiet: "静かな", quit: "辞める", quiz: "小テスト", ramen: "ラーメン",
  rather: "むしろ", reach: "達する", read: "読む", reader: "読者",
  ready: "準備ができた", really: "本当に", rebook: "予約し直す", receive: "受け取る",
  recently: "最近", recommendation: "おすすめ", record: "記録する",
  registration: "登録", regret: "後悔", regular: "定期的な", release: "リリース",
  reluctant: "気が進まない", remain: "〜のままである", remember: "覚えている",
  remove: "取り除く", renewable: "再生可能な", repetition: "反復",
  replacement: "代替の", replicate: "再現する", reply: "返信", report: "報告書",
  require: "必要とする", researcher: "研究者", respond: "応答する", result: "結果",
  return: "戻る", revolution: "革命", reward: "報酬", right: "正しい・右",
  rise: "上昇する", river: "川", roadmap: "ロードマップ", room: "部屋",
  rose: "上がった", route: "経路", routine: "日課", safe: "安全な", sale: "売上",
  same: "同じ", sandwich: "サンドイッチ", saturday: "土曜日",
  save: "節約する・保存する", say: "言う", school: "学校", science: "科学",
  screen: "画面", season: "シーズン", second: "2番目の・秒", section: "セクション",
  see: "見る", seen: "見た", segment: "部門", self: "自己", seminar: "ゼミ",
  send: "送る", sent: "送った", sentence: "文", september: "9月",
  serve: "提供する", service: "サービス", session: "回・セッション", seven: "7",
  share: "共有する", sharp: "ちょうど", sharply: "急激に", she: "彼女",
  shoe: "靴", shopper: "買い物客", shopping: "買い物", short: "短い",
  shortage: "不足", should: "〜すべき", shown: "示された", sick: "病気の",
  side: "側・味方", significantly: "大幅に", since: "〜以来・〜なので",
  sister: "姉妹", site: "場所・観光地", six: "6", size: "大きさ", skill: "技能",
  slack: "Slack（チャットツール）", sleep: "睡眠", slept: "眠った",
  slide: "スライド", slightly: "わずかに", slot: "枠", slowly: "ゆっくり",
  small: "小さい", smith: "スミス（人名）", smoking: "喫煙", so: "だから",
  sold: "売れた", solution: "解決策", some: "いくつかの", someone: "誰か",
  something: "何か", sometime: "いつか", soon: "すぐに", sorry: "ごめんなさい",
  speaker: "話者", specifically: "具体的に", spent: "過ごした", square: "広場",
  stable: "安定した", staff: "スタッフ", start: "始める", station: "駅",
  status: "状況", stay: "泊まる・とどまる", step: "手順", still: "まだ",
  stop: "止まる・停留所", store: "店", storm: "嵐", story: "話", street: "通り",
  stress: "ストレス", strike: "ストライキ", strong: "強い", structure: "構造",
  student: "学生", suggest: "提案する", sum: "まとめる・合計", summer: "夏",
  sunday: "日曜日", support: "支援する", supporter: "支持者", surface: "表面",
  surprise: "サプライズ", survive: "生き残る", sushi: "寿司", suspend: "運休にする",
  switching: "切り替え", tale: "話・教訓", ta: "TA（教育助手）", tax: "税",
  taxi: "タクシー", teacher: "先生", team: "チーム", technical: "技術的な",
  tell: "伝える", ten: "10", terrifying: "怖い", test: "テスト",
  textbook: "教科書", than: "〜より", thank: "感謝する", that: "それ",
  "that's": "それは〜だ", them: "彼らを", then: "それから", theory: "理論",
  there: "そこ", "there's": "そこに〜がある", therefore: "したがって",
  these: "これら", they: "彼ら", think: "思う", thirty: "30", this: "これ",
  those: "それら", though: "〜だけれども", thought: "思った", three: "3",
  through: "〜を通って", thursday: "木曜日", ticket: "チケット",
  timeline: "時期・予定", tiny: "とても小さい", tired: "疲れた", today: "今日",
  tokyo: "東京", told: "伝えた", tomorrow: "明日", tonight: "今夜",
  too: "〜も・〜すぎる", took: "取った・かかった", topic: "話題", tough: "大変な",
  tourism: "観光", tourist: "観光客", town: "町", track: "順調・軌道",
  traffic: "交通・渋滞", trail: "山道", train: "電車", travel: "旅行",
  treat: "おごり", tree: "木", triple: "3倍になる", true: "本当の",
  tuesday: "火曜日", turn: "順番・曲がる", twenty: "20", twice: "2回", two: "2",
  understand: "理解する", unforgettable: "忘れられない", uniform: "制服",
  university: "大学", unless: "〜でない限り", unreal: "現実離れした",
  unregulated: "規制のない", until: "〜まで", upgrade: "アップグレード",
  upload: "アップロードする", upstairs: "2階の", us: "私たちを", use: "使う",
  useful: "役に立つ", value: "価値", vary: "異なる", venice: "ベネチア",
  very: "とても", video: "ビデオ", view: "景色・見方", visit: "訪問",
  visitor: "来訪者", vote: "投票する", wait: "待つ", want: "欲しい",
  was: "〜だった", watch: "見る", water: "水", we: "私たち", "we're": "私たちは〜だ",
  weak: "弱い", weaken: "弱める", wear: "着る", weather: "天気",
  wednesday: "水曜日", week: "週", weekend: "週末", welcome: "ようこそ",
  well: "よく・うまく", went: "行った", were: "〜だった", what: "何",
  whatever: "何でも", when: "いつ", where: "どこ", "where's": "どこに〜がある",
  which: "どちら", while: "〜する間", white: "白", who: "誰", whole: "全体の",
  why: "なぜ", widely: "広く", wifi: "Wi-Fi", will: "〜だろう", winter: "冬",
  with: "〜と一緒に", within: "〜以内に", without: "〜なしで", woman: "女性",
  word: "単語", worker: "労働者", worry: "心配する", would: "〜だろう",
  write: "書く", wrote: "書いた", year: "年", yesterday: "昨日",
  york: "ヨーク（New York）", you: "あなた", "you're": "あなたは〜だ",
  your: "あなたの", yuki: "ユキ（人名）", zero: "ゼロ",

  /* 機能語・高頻度語 */
  the: "その（定冠詞）", to: "〜へ・〜すること", a: "一つの", for: "〜のために",
  in: "〜の中に", on: "〜の上に・〜に", and: "そして", of: "〜の",
  "i'm": "私は〜です", me: "私を", it: "それ", by: "〜によって・〜までに",
  time: "時間", work: "働く・うまくいく", up: "上へ", be: "〜である",
  about: "〜について", check: "確認する", essay: "エッセイ・小論文", how: "どのように",
  get: "得る・着く", late: "遅い", main: "主な", make: "作る", give: "与える",
  out: "外へ", flight: "便・フライト", take: "取る・かかる", no: "いいえ・〜がない",
  office: "オフィス", study: "勉強（する）", data: "データ", finally: "ついに",
  claim: "主張（する）", keep: "保つ", question: "質問", review: "見直す・レビュー",
  group: "グループ", local: "地元の", trip: "旅行", way: "方法・道",
  answer: "答え", left: "置き忘れた・左", boarding: "搭乗", run: "走る・運行する",
  lost: "失った・迷った", sure: "確かな", point: "点・指摘", together: "一緒に",
  remote: "遠隔の", show: "見せる・示す", order: "注文（する）", sound: "〜に聞こえる",
  try: "試す", good: "良い", "what's": "何が〜ですか", idea: "考え",
  never: "決して〜ない", connecting: "乗り継ぎの", pass: "通行証・渡す",
  tour: "ツアー", baggage: "手荷物", follow: "従う・続く", forward: "前へ",
  security: "保安・セキュリティ", hand: "手・手渡す", look: "見る",
  figure: "考え出す・数字", final: "最終の", count: "数える・数",
  context: "文脈", mind: "気にする・心", contrast: "対照", exam: "試験",
  down: "下へ", sample: "見本", catch: "捕まえる・間に合う", exchange: "交換",
  round: "往復の・丸い", seat: "席", passport: "パスポート", found: "見つけた",
  list: "一覧", reference: "参考", hang: "待つ・掛ける", only: "〜だけ",
  counter: "カウンター", as: "〜として・〜のとき", control: "調整する・管理",
  earlier: "以前の", mainly: "主に", thing: "こと・もの", saving: "貯金・節約",
  rate: "率・レート", window: "窓", aisle: "通路", guided: "ガイド付きの",
  specialty: "名物・特産", limited: "限られた", performance: "業績・成績",
  peer: "同僚・同輩", extension: "延長", literature: "文献・文学",
  analysis: "分析", detailed: "詳しい", multiple: "複数の", choice: "選択",
  fill: "埋める", blank: "空欄", detail: "詳細", clue: "手がかり",
  limit: "制限", passed: "合格した・過ぎた", kind: "親切な・種類",
  into: "〜の中へ", errand: "用事", along: "〜に沿って", drop: "落とす・立ち寄る",
  break: "休憩・壊す", tried: "試した", head: "向かう・頭", deal: "取引・こと",
  easy: "簡単な", touch: "連絡・触れる", its: "それの", computer: "コンピューター",
  reading: "読解・読むこと", talk: "話す", accept: "受け入れる",
  driven: "牽引された", tap: "蛇口", sam: "サム（人名）",

  /* ハイフンでつながった複合語 */
  "check-in": "チェックイン", "small-business": "中小企業の",
  "two-factor": "二要素の", "self-discipline": "自己管理",
  "in-person": "対面の", "open-book": "持ち込み可の",
  "self-expression": "自己表現", "three-hour": "3時間の"
};

// 熟語・イディオム辞書。単語デッキ側の複合語（boarding pass など）は
// app.js の buildPhraseIndex() が自動で取り込むため、ここには書かない。
// 活用形は lookupWord と同じ正規化で照合するので、原形で登録すればよい。
window.PhraseGlossary = {
  /* 依頼・丁寧表現 */
  "could you": "〜していただけますか", "could i": "〜してもよいですか",
  "would you": "〜していただけますか", "would like": "〜したいのですが",
  "i'd like": "〜したいのですが", "i would like": "〜したいのですが",
  "thank you": "ありがとう", "thank you for": "〜をありがとう",
  "excuse me": "すみません", "let me know": "知らせてください",
  "let me": "私に〜させてください", "please find attached": "添付をご確認ください",
  "look forward to": "〜を楽しみにする", "make sure": "確かめる・必ず〜する",
  "feel free to": "遠慮なく〜してください", "as soon as possible": "できるだけ早く",
  "in advance": "前もって", "get back to": "〜に折り返し連絡する",
  "i'm afraid": "申し訳ありませんが", "would you mind": "〜していただけませんか",

  /* 句動詞 */
  "follow up": "追って確認する", "sort out": "解決する・整理する",
  "put off": "延期する", "call off": "中止する", "turn down": "断る・下げる",
  "bring up": "話題に出す", "point out": "指摘する", "carry out": "実行する",
  "set up": "設定する・準備する", "come up with": "思いつく",
  "deal with": "対処する", "look into": "調べる", "check out": "確認する・退出する",
  "check in": "チェックインする", "run out of": "〜を切らす",
  "take care of": "世話をする・対処する", "end up": "結局〜になる",
  "work out": "うまくいく・運動する", "find out": "見つけ出す・分かる",
  "go over": "見直す", "go through": "経験する・目を通す", "hold on": "待つ",
  "hang up": "電話を切る", "pick up": "拾う・迎えに行く", "drop off": "届ける・降ろす",
  "fill out": "記入する", "fill in": "記入する", "hand out": "配る",
  "sign up": "申し込む", "log in": "ログインする", "back up": "バックアップする",
  "break down": "故障する", "cut down": "削減する", "keep up": "遅れずについていく",
  "make up": "埋め合わせる・作り上げる", "put together": "まとめる",
  "turn in": "提出する", "look after": "世話をする", "run into": "偶然出会う",
  "give up": "あきらめる", "take over": "引き継ぐ", "stand out": "目立つ",
  "come across": "出くわす", "get by": "何とかやっていく", "put up with": "我慢する",

  /* 動詞句・慣用句 */
  "take place": "開催される", "take part": "参加する", "make sense": "筋が通る",
  "make a difference": "違いを生む", "pay attention": "注意を払う",
  "keep in mind": "心に留めておく", "take a look": "見てみる",
  "have a look": "見てみる", "take time": "時間がかかる",
  "make time": "時間を作る", "save time": "時間を節約する",
  "in charge": "担当して", "on behalf of": "〜を代表して",
  "take responsibility": "責任を取る", "reach out": "連絡を取る",
  "touch base": "軽く連絡を取る", "move forward": "前に進める",
  "keep track of": "把握しておく", "focus on": "〜に集中する",
  "depend on": "〜次第である", "based on": "〜に基づいて",
  "result in": "〜という結果になる", "lead to": "〜につながる",
  "apply for": "〜に応募する", "apply to": "〜に当てはまる",
  "ask for": "〜を求める", "wait for": "〜を待つ", "look for": "〜を探す",
  "care about": "〜を気にかける", "worry about": "〜を心配する",
  "think about": "〜について考える", "talk about": "〜について話す",
  "agree with": "〜に賛成する", "disagree with": "〜に反対する",

  /* つなぎ表現・副詞句 */
  "by the way": "ところで", "of course": "もちろん", "at the moment": "今のところ",
  "in person": "直接会って", "so far": "今のところ", "as well": "〜も同様に",
  "as well as": "〜と同様に", "such as": "〜のような", "instead of": "〜の代わりに",
  "rather than": "〜よりむしろ", "according to": "〜によれば",
  "in addition": "加えて", "on the other hand": "一方で",
  "as a result": "その結果", "for example": "例えば", "for instance": "例えば",
  "in fact": "実際", "at first": "最初は", "after all": "結局",
  "no longer": "もはや〜ない", "a lot of": "たくさんの", "a bit": "少し",
  "a little": "少し", "at least": "少なくとも", "at most": "多くとも",
  "up to": "最大〜まで・〜次第", "due to": "〜のせいで", "thanks to": "〜のおかげで",
  "prior to": "〜より前に", "regardless of": "〜に関わらず",
  "as long as": "〜する限り", "even though": "〜だけれども",
  "in order to": "〜するために", "so that": "〜するように",
  "as if": "まるで〜のように", "in terms of": "〜の観点では",
  "in case": "〜の場合に備えて", "on time": "時間通りに", "in time": "間に合って",
  "right away": "すぐに", "all day": "一日中", "these days": "最近",
  "at the same time": "同時に", "more than": "〜より多く",
  "less than": "〜より少なく", "as much as": "〜と同じくらい",
  "each other": "お互いに", "one another": "お互いに",
  "in general": "一般的に", "in particular": "特に", "above all": "とりわけ",
  "on the whole": "全体として", "to be honest": "正直に言うと",
  "in short": "要するに", "that is": "つまり", "in other words": "言い換えると",

  /* 助動詞的表現 */
  "used to": "以前は〜だった", "be able to": "〜できる",
  "be supposed to": "〜することになっている", "had better": "〜した方がよい",
  "have to": "〜しなければならない", "need to": "〜する必要がある",
  "want to": "〜したい", "going to": "〜するつもり", "plan to": "〜する予定",
  "decide to": "〜すると決める", "manage to": "何とか〜する",
  "try to": "〜しようとする", "seem to": "〜のようだ",
  "would rather": "むしろ〜したい", "might as well": "〜した方がましだ",

  /* 日常会話 */
  "how about": "〜はどうですか", "what about": "〜はどうですか",
  "how come": "どうして", "no problem": "問題ありません",
  "never mind": "気にしないで", "you're welcome": "どういたしまして",
  "see you": "またね", "take care": "気をつけて", "good luck": "頑張って",
  "long time no see": "久しぶり", "not at all": "全然そんなことない",
  "sounds like": "〜のようですね", "i see": "なるほど",
  "by all means": "ぜひどうぞ", "just in case": "念のため"
};

// 活用形での照合を許さない固定表現。
// 例: 別れの挨拶 "see you" は、"looking forward to seeing you"（実際に会う）に
// 誤って当たってしまうため、字面どおりのときだけ熟語として扱う。
window.PhraseExact = [
  "see you", "take care", "good luck", "long time no see", "not at all",
  "i see", "no problem", "never mind", "you're welcome", "of course",
  "by all means", "how come", "that is", "in fact", "at first",
  "after all", "as well", "so far", "a bit", "a little"
];
